<?php


namespace Tests\AppBundle\Controller;

use AppBundle\DataFixtures\ORM\LoadNotas;
use Liip\FunctionalTestBundle\Test\WebTestCase;

class NotasControllerTest extends WebTestCase
{

    protected $fixtures;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fixtures = $this->loadFixtures(array(
           LoadNotas::class
        ))->getReferenceRepository();
    }

    /**
     * @test
     */
    public function testCrearNota()
    {
        $client = $this->makeClient();

        $client->request('POST', '/api/nota', array('texto' => 'NOTA PRUEBA'));

        $this->isSuccessful($client->getResponse());
    }

    /**
     * @test
     */
    public function testMarcarFavorita()
    {

        $client = $this->makeClient();
        $idNota = $this->fixtures->getReference('nota-1')->getId();
        $client->request('PUT', '/api/nota/'.$idNota.'/favorita');

        $this->isSuccessful($client->getResponse());

    }

    /**
     * @test
     */
    public function testGetNotas()
    {
        $client = $this->makeClient();
        $client->request('GET', '/api/notas');

        $this->isSuccessful($client->getResponse());

    }

    /**
     * @test
     */
    public function testGetNota()
    {
        $client = $this->makeClient();
        $idNota = $this->fixtures->getReference('nota-1')->getId();

        $client->request('GET', '/api/nota/' . $idNota);

        $this->isSuccessful($client->getResponse());
    }


    /**
     * @test
     */
    public function testGetNotasFavoritas()
    {
        $client = $this->makeClient();
        $client->request('GET', '/api/notas/favoritas');

        $this->isSuccessful($client->getResponse());
    }

}